import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { RecoilWrapper } from './RecoilWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <RecoilWrapper>
        <body className={`${inter.className} light-theme`}>{children}</body>
      </RecoilWrapper>
    </html>
  );
}
